import type { ProductKind } from './types';

/* ===========================================================================
   What the studio can design.

   Each kind declares its artboard, the blocks the composer may draw from and
   any additional frames worth generating (a second screen, the back of a card,
   a third slide). The composer decides which of the allowed blocks actually
   appear, in what order and in which variant — this list is a vocabulary, not
   a layout.
   =========================================================================== */

const PAGE = { kind: 'page', label: 'Десктоп 1440', labelKey: 'canvas.page', width: 1440, chrome: 'browser' } as const;
const PHONE = { kind: 'mobile', label: 'Телефон 390×844', labelKey: 'canvas.phone', width: 390, height: 844, chrome: 'phone' } as const;
const DESKTOP_APP = { kind: 'app', label: 'Приложение 1440×900', labelKey: 'canvas.app', width: 1440, height: 900, chrome: 'desktop' } as const;

export const PRODUCTS: ProductKind[] = [
  /* ------------------------------- веб ------------------------------- */
  {
    id: 'site',
    label: 'Сайт',
    group: 'Веб',
    note: 'Многостраничный сайт компании или проекта',
    labelKey: 'product.site',
    noteKey: 'product.site.note',
    groupKey: 'product.group.web',
    canvas: PAGE,
    blocks: ['nav', 'hero', 'logos', 'features', 'showcase', 'stats', 'process', 'team', 'testimonials', 'faq', 'cta', 'contactForm', 'footer'],
    required: ['nav', 'hero', 'footer'],
    extraFrames: [{ name: 'Внутренняя страница', blocks: ['nav', 'pageHeader', 'features', 'gallery', 'cta', 'footer'] }],
  },
  {
    id: 'landing',
    label: 'Лендинг',
    group: 'Веб',
    note: 'Одностраничник под один оффер и одно действие',
    labelKey: 'product.landing',
    noteKey: 'product.landing.note',
    groupKey: 'product.group.web',
    canvas: PAGE,
    blocks: ['nav', 'hero', 'logos', 'features', 'bento', 'showcase', 'stats', 'steps', 'pricing', 'testimonials', 'faq', 'cta', 'footer'],
    required: ['nav', 'hero', 'cta', 'footer'],
  },
  {
    id: 'shop',
    label: 'Интернет-магазин',
    group: 'Веб',
    note: 'Витрина, каталог и карточка товара',
    labelKey: 'product.shop',
    noteKey: 'product.shop.note',
    groupKey: 'product.group.web',
    canvas: PAGE,
    blocks: ['nav', 'hero', 'categories', 'catalog', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    required: ['nav', 'hero', 'catalog', 'footer'],
    extraFrames: [{ name: 'Карточка товара', blocks: ['nav', 'productDetail', 'catalog', 'footer'] }],
  },
  {
    id: 'portfolio',
    label: 'Портфолио',
    group: 'Веб',
    note: 'Работы, подход и контакт',
    labelKey: 'product.portfolio',
    noteKey: 'product.portfolio.note',
    groupKey: 'product.group.web',
    canvas: PAGE,
    blocks: ['nav', 'hero', 'showcase', 'gallery', 'bento', 'stats', 'process', 'testimonials', 'cta', 'footer'],
    required: ['nav', 'hero', 'showcase', 'footer'],
  },
  {
    id: 'auth',
    label: 'Авторизация и регистрация',
    group: 'Веб',
    note: 'Экраны входа, регистрации и восстановления',
    labelKey: 'product.auth',
    noteKey: 'product.auth.note',
    groupKey: 'product.group.web',
    canvas: { kind: 'page', label: 'Десктоп 1440×900', labelKey: 'canvas.pageFixed', width: 1440, height: 900, chrome: 'browser' },
    blocks: ['authForm'],
    required: ['authForm'],
    extraFrames: [{ name: 'Регистрация', blocks: ['authForm'] }],
  },

  /* ---------------------------- интерфейсы ---------------------------- */
  {
    id: 'mobileApp',
    label: 'Мобильное приложение',
    group: 'Интерфейсы',
    note: 'Экраны приложения под iOS и Android',
    labelKey: 'product.mobileApp',
    noteKey: 'product.mobileApp.note',
    groupKey: 'product.group.interfaces',
    canvas: PHONE,
    blocks: ['mobileHeader', 'mobileHero', 'mobileChips', 'mobileCards', 'mobileList', 'mobileStats', 'tabbar'],
    required: ['mobileHeader', 'tabbar'],
    extraFrames: [
      { name: 'Каталог', blocks: ['mobileHeader', 'mobileChips', 'mobileCards', 'tabbar'] },
      { name: 'Профиль', blocks: ['mobileHeader', 'mobileStats', 'mobileList', 'tabbar'] },
    ],
  },
  {
    id: 'dashboard',
    label: 'Панель администратора',
    group: 'Интерфейсы',
    note: 'Дашборд с метриками, графиками и таблицами',
    labelKey: 'product.dashboard',
    noteKey: 'product.dashboard.note',
    groupKey: 'product.group.interfaces',
    canvas: DESKTOP_APP,
    blocks: ['kpis', 'chart', 'table', 'activity', 'board'],
    required: ['kpis'],
    extraFrames: [{ name: 'Раздел отчётов', blocks: ['kpis', 'table', 'activity'] }],
  },
  {
    id: 'crm',
    label: 'CRM / ERP',
    group: 'Интерфейсы',
    note: 'Рабочее место оператора: списки, карточки, статусы',
    labelKey: 'product.crm',
    noteKey: 'product.crm.note',
    groupKey: 'product.group.interfaces',
    canvas: DESKTOP_APP,
    blocks: ['kpis', 'board', 'table', 'activity', 'chart'],
    required: ['table'],
    extraFrames: [{ name: 'Карточка сделки', blocks: ['board', 'activity'] }],
  },
  {
    id: 'service',
    label: 'Интерфейс сервиса',
    group: 'Интерфейсы',
    note: 'Веб-приложение с рабочей областью',
    labelKey: 'product.service',
    noteKey: 'product.service.note',
    groupKey: 'product.group.interfaces',
    canvas: DESKTOP_APP,
    blocks: ['kpis', 'chart', 'board', 'table', 'activity'],
    required: ['board'],
  },
  {
    id: 'uiKit',
    label: 'UI-компоненты',
    group: 'Интерфейсы',
    note: 'Библиотека элементов и состояний',
    labelKey: 'product.uiKit',
    noteKey: 'product.uiKit.note',
    groupKey: 'product.group.interfaces',
    canvas: { kind: 'kit', label: 'Лист 1280', labelKey: 'canvas.kit', width: 1280, chrome: 'none' },
    blocks: ['uiKit'],
    required: ['uiKit'],
  },

  /* ----------------------------- графика ----------------------------- */
  {
    id: 'logo',
    label: 'Логотип',
    group: 'Графика',
    note: 'Знак, логотип и правила построения',
    labelKey: 'product.logo',
    noteKey: 'product.logo.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'logo', label: 'Артборд 900×700', labelKey: 'canvas.logo', width: 900, height: 700, chrome: 'none' },
    blocks: ['logoMark'],
    required: ['logoMark'],
    extraFrames: [
      { name: 'Варианты и цвета', blocks: ['logoVariants'] },
      { name: 'Носители', blocks: ['logoUsage'] },
    ],
  },
  {
    id: 'banner',
    label: 'Рекламный баннер',
    group: 'Графика',
    note: 'Горизонтальный баннер для веба',
    labelKey: 'product.banner',
    noteKey: 'product.banner.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'poster', label: 'Баннер 1200×628', labelKey: 'canvas.banner', width: 1200, height: 628, chrome: 'none' },
    blocks: ['poster'],
    required: ['poster'],
    extraFrames: [{ name: 'Вертикальный формат', blocks: ['posterTall'] }],
  },
  {
    id: 'social',
    label: 'Пост для соцсетей',
    group: 'Графика',
    note: 'Квадратный пост и сторис',
    labelKey: 'product.social',
    noteKey: 'product.social.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'poster', label: 'Пост 1080×1080', labelKey: 'canvas.social', width: 1080, height: 1080, chrome: 'none' },
    blocks: ['poster'],
    required: ['poster'],
    extraFrames: [{ name: 'Сторис 1080×1920', blocks: ['posterStory'] }],
  },
  {
    id: 'ad',
    label: 'Рекламные материалы',
    group: 'Графика',
    note: 'Плакат или афиша под печать и digital',
    labelKey: 'product.ad',
    noteKey: 'product.ad.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'poster', label: 'Плакат 1080×1350', labelKey: 'canvas.poster', width: 1080, height: 1350, chrome: 'none' },
    blocks: ['posterTall'],
    required: ['posterTall'],
  },
  {
    id: 'presentation',
    label: 'Презентация',
    group: 'Графика',
    note: 'Титул, содержательные слайды и финал',
    labelKey: 'product.presentation',
    noteKey: 'product.presentation.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'slide', label: 'Слайд 1600×900', labelKey: 'canvas.slide', width: 1600, height: 900, chrome: 'none' },
    blocks: ['slideTitle'],
    required: ['slideTitle'],
    extraFrames: [
      { name: 'Слайд с контентом', blocks: ['slideContent'] },
      { name: 'Слайд с цифрами', blocks: ['slideStats'] },
    ],
  },
  {
    id: 'businessCard',
    label: 'Визитная карточка',
    group: 'Графика',
    note: 'Лицевая и оборотная стороны, 90×50 мм',
    labelKey: 'product.businessCard',
    noteKey: 'product.businessCard.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'card', label: 'Визитка 1063×591', labelKey: 'canvas.card', width: 1063, height: 591, chrome: 'paper' },
    blocks: ['cardFront'],
    required: ['cardFront'],
    extraFrames: [{ name: 'Оборот', blocks: ['cardBack'] }],
  },
  {
    id: 'email',
    label: 'Email-шаблон',
    group: 'Графика',
    note: 'Письмо шириной 600px под почтовые клиенты',
    labelKey: 'product.email',
    noteKey: 'product.email.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'email', label: 'Письмо 600', labelKey: 'canvas.email', width: 600, chrome: 'paper' },
    blocks: ['emailHeader', 'emailHero', 'emailCards', 'emailCta', 'emailFooter'],
    required: ['emailHeader', 'emailHero', 'emailFooter'],
  },
  {
    id: 'productCard',
    label: 'Карточка товара',
    group: 'Графика',
    note: 'Карточка для маркетплейса или каталога',
    labelKey: 'product.productCard',
    noteKey: 'product.productCard.note',
    groupKey: 'product.group.graphics',
    canvas: { kind: 'card', label: 'Карточка 900×1200', labelKey: 'canvas.productCard', width: 900, height: 1200, chrome: 'none' },
    blocks: ['productCard'],
    required: ['productCard'],
  },
];

export const getProduct = (id: string): ProductKind =>
  PRODUCTS.find((product) => product.id === id) ?? PRODUCTS[0];

/** Picker groups, in display order. */
export const PRODUCT_GROUPS = ['Веб', 'Интерфейсы', 'Графика'];
