import type { Vocabulary } from './types';

/* English copy. Written rather than translated: headlines and offers do not
   survive word-for-word transfer, so each domain says the same thing its
   Russian counterpart says, in the way English marketing copy says it. */

const en: Vocabulary = {
  domains: [
    {
      id: 'food',
      label: 'food and drink',
      keywords: ['restaurant', 'cafe', 'coffee', 'kitchen', 'menu', 'food', 'delivery', 'bakery', 'bar', 'pizza', 'sushi', 'grocer', 'farm'],
      brands: ['Tract', 'Grain', 'Noon', 'Sheaf', 'Copper'],
      nav: ['Menu', 'About', 'Delivery', 'Events', 'Contact'],
      headlines: [
        'Cooked over fire, and in season',
        'Food worth coming back for',
        'Ingredients you can trace',
        'A fresh batch every morning',
      ],
      subtitles: [
        'The menu follows whatever the farmers and fishermen bring in that week.',
        'An open kitchen, a short ingredient list and portions that make sense.',
        'Delivered the day it is picked — under a day from field to table.',
      ],
      items: [
        { title: 'Beef tartare', meta: 'smoked yolk, mustard' },
        { title: 'Charcoal sea bream', meta: 'lemon, thyme, fennel' },
        { title: 'Rack of lamb', meta: 'aubergine, mint, yoghurt' },
        { title: 'Root vegetables', meta: 'cream sauce, herbs' },
        { title: 'Pumpkin soup', meta: 'pine nuts, sage' },
        { title: 'Sourdough bread', meta: 'spelt, 18-hour prove' },
        { title: 'Farmhouse curd pancakes', meta: 'rhubarb jam' },
        { title: 'Spiced mulled wine', meta: 'red wine, citrus, star anise' },
      ],
      stats: [
        { value: '12', label: 'years on the waterfront' },
        { value: '480', label: 'guests a week' },
        { value: '4.9', label: 'average rating' },
        { value: '6', label: 'weeks per menu cycle' },
      ],
      categories: ['Breakfast', 'Small plates', 'From the oven', 'Pasta', 'Desserts', 'Drinks'],
      imagery: ['the dining room in evening light', 'a dish close up on dark ceramic', 'the chef at the open kitchen'],
    },
    {
      id: 'tech',
      label: 'digital product',
      keywords: ['saas', 'platform', 'app', 'crm', 'erp', 'analytics', 'automation', 'integration', 'dashboard', 'data', 'cloud', 'software', 'ai', 'neural'],
      brands: ['Flowdesk', 'Contour', 'Orbit', 'Severus', 'Console'],
      nav: ['Features', 'Pricing', 'Integrations', 'Docs', 'Blog'],
      headlines: [
        'Your whole team in one window',
        'Put the busywork on autopilot',
        'Numbers that finally agree',
        'Live in a day, paid back in a month',
      ],
      subtitles: [
        'Enquiries, tasks and reports in one place — no ten open tabs, no manual exports.',
        'Connects to what you already use and takes the repetitive work off your hands.',
        'Custom dashboards, access rights and a full change history out of the box.',
      ],
      items: [
        { title: 'One pipeline', meta: 'every channel in a single list' },
        { title: 'Automations', meta: 'rules without a line of code' },
        { title: 'Reports', meta: 'builder and scheduled exports' },
        { title: 'Permissions', meta: 'roles, teams, action audit' },
        { title: 'API and webhooks', meta: 'documentation and a sandbox' },
        { title: 'Mobile access', meta: 'works offline, syncs later' },
        { title: 'Data import', meta: 'move off spreadsheets in minutes' },
        { title: 'Notifications', meta: 'email, chat, push' },
      ],
      stats: [
        { value: '3,200+', label: 'teams working daily' },
        { value: '99.9%', label: 'uptime this year' },
        { value: '−41%', label: 'time spent reporting' },
        { value: '18', label: 'ready integrations' },
      ],
      categories: ['Sales', 'Tasks', 'Analytics', 'Finance', 'Team', 'Settings'],
      imagery: ['the product on a laptop at a desk', 'a dashboard close up', 'the team reviewing a board'],
    },
    {
      id: 'shop',
      label: 'retail',
      keywords: ['shop', 'store', 'product', 'catalogue', 'catalog', 'cart', 'buy', 'sale', 'brand', 'collection', 'jewellery', 'furniture', 'clothing', 'marketplace'],
      brands: ['House and Light', 'Carat', 'Solid', 'Shelf', 'Luna'],
      nav: ['Catalogue', 'New in', 'Collections', 'Delivery', 'Contact'],
      headlines: [
        'Things that last for years',
        'The new collection is in stock',
        'Made by hand, shipped today',
        'The kind you end up keeping',
      ],
      subtitles: [
        'We buy straight from the workshops — no middleman markup, no compromise on material.',
        'Free delivery over £50 and thirty days to return anything, no questions asked.',
        'Every piece is on the shelf — orders leave the same day.',
      ],
      items: [
        { title: 'Oval table lamp', meta: 'brass, fabric shade' },
        { title: 'Tor armchair', meta: 'solid oak, wool' },
        { title: 'Layer vase', meta: 'hand-blown glass, 28 cm' },
        { title: 'Pine throw', meta: 'merino, 140×200' },
        { title: 'Line dresser', meta: 'ash veneer, four drawers' },
        { title: 'Circle mirror', meta: 'oak, 70 cm across' },
        { title: 'Ridge candleholder', meta: 'ceramic, set of three' },
        { title: 'Field rug', meta: 'wool, 200×300' },
      ],
      stats: [
        { value: '4,800', label: 'orders this year' },
        { value: '30 days', label: 'to return' },
        { value: '4.8', label: 'customer rating' },
        { value: '2 days', label: 'average delivery' },
      ],
      categories: ['Lighting', 'Furniture', 'Textiles', 'Decor', 'Tableware', 'Sale'],
      imagery: ['product shot on a plain background', 'the piece in a room', 'the collection laid out from above'],
    },
    {
      id: 'health',
      label: 'health',
      keywords: ['clinic', 'medical', 'doctor', 'dental', 'dentist', 'health', 'veterinary', 'appointment', 'diagnostic', 'treatment', 'optician', 'lab'],
      brands: ['Medea', 'Paw', 'Smile+', 'Focus', 'Norma'],
      nav: ['Services', 'Doctors', 'Prices', 'Reviews', 'Contact'],
      headlines: [
        'Care that explains itself',
        'An appointment this week, not next month',
        'Diagnosis first, treatment second',
        'The same doctor from start to finish',
      ],
      subtitles: [
        'We tell you what we found, what it means and what the alternatives cost.',
        'Equipment and protocols you can look up, run by specialists you can name.',
        'Booking takes a minute and the price is agreed before anything begins.',
      ],
      items: [
        { title: 'Initial consultation', meta: '40 minutes, with a written summary' },
        { title: 'Ultrasound', meta: 'results explained the same day' },
        { title: 'Blood panel', meta: 'own laboratory, next-day results' },
        { title: 'Preventive check-up', meta: 'a yearly programme by age' },
        { title: 'Dental hygiene', meta: 'ultrasound and polishing' },
        { title: 'Paediatric appointment', meta: 'unhurried, with a parent present' },
        { title: 'Second opinion', meta: 'a review of an existing diagnosis' },
        { title: 'Home visit', meta: 'within the city, on the day' },
      ],
      stats: [
        { value: '14', label: 'specialists on staff' },
        { value: '24 h', label: 'to most results' },
        { value: '4.9', label: 'patient rating' },
        { value: '9', label: 'years of practice' },
      ],
      categories: ['General', 'Diagnostics', 'Surgery', 'Paediatrics', 'Prevention', 'Rehabilitation'],
      imagery: ['a bright consulting room', 'a specialist with a patient', 'clean equipment close up'],
    },
    {
      id: 'beauty',
      label: 'beauty and grooming',
      keywords: ['salon', 'beauty', 'hair', 'barber', 'nails', 'spa', 'brows', 'lashes', 'makeup', 'tattoo', 'stylist', 'grooming'],
      brands: ['Sheen', 'Razor', 'Tone', 'Ritual', 'Needle'],
      nav: ['Services', 'Stylists', 'Work', 'Prices', 'Booking'],
      headlines: [
        'You will recognise yourself',
        'Booked in a minute, done in an hour',
        'A cut that grows out well',
        'The same hands every time',
      ],
      subtitles: [
        'We start with a conversation about what you actually want to live with day to day.',
        'Prices are per service, not per surprise — you know the total before we start.',
        'Every stylist keeps their own portfolio, so you choose the work, not the slot.',
      ],
      items: [
        { title: "Women's cut and styling", meta: 'consultation included' },
        { title: 'Colour correction', meta: 'from two to five hours' },
        { title: 'Highlights', meta: 'gentle formulas, toning included' },
        { title: "Men's cut", meta: 'clipper and scissor work' },
        { title: 'Beard shaping', meta: 'hot towel, finishing oil' },
        { title: 'Manicure with coating', meta: 'lasts three to four weeks' },
        { title: 'Brow shaping', meta: 'shape, tint, lamination' },
        { title: 'Facial care', meta: 'cleanse by skin type' },
      ],
      stats: [
        { value: '8', label: 'stylists in the studio' },
        { value: '4.9', label: 'rating over 600 visits' },
        { value: '70%', label: 'of clients come back' },
        { value: '6', label: 'years open' },
      ],
      categories: ['Hair', 'Nails', 'Face', 'Body', 'Brows and lashes', "Men's room"],
      imagery: ['the studio interior in daylight', 'a before and after pair', 'hands at work, close up'],
    },
    {
      id: 'education',
      label: 'education',
      keywords: ['course', 'school', 'training', 'education', 'learn', 'teacher', 'lesson', 'workshop', 'academy', 'tutor', 'class', 'diploma'],
      brands: ['Vector', 'Orange', 'Step', 'Faculty', 'Practicum'],
      nav: ['Courses', 'Teachers', 'Schedule', 'Fees', 'Contact'],
      headlines: [
        'Learn it by doing it',
        'A portfolio, not a certificate',
        'Small groups, real feedback',
        'From first lesson to first job',
      ],
      subtitles: [
        'Every module ends with something you made, reviewed by someone who does this for a living.',
        'Groups cap at twelve so nobody spends the term at the back of the room.',
        'Evening and weekend streams, recorded, so a missed week is not a lost one.',
      ],
      items: [
        { title: 'Intensive: fundamentals', meta: 'eight weeks, twice a week' },
        { title: 'Full course', meta: 'six months with a final project' },
        { title: 'Weekend workshop', meta: 'one topic, two days' },
        { title: 'Mentoring', meta: 'one to one, hourly' },
        { title: "Children's programme", meta: 'ages 9 to 14' },
        { title: 'Corporate training', meta: 'tailored to your team' },
        { title: 'Portfolio review', meta: 'a written verdict in three days' },
        { title: 'Open lecture', meta: 'free, once a month' },
      ],
      stats: [
        { value: '1,400', label: 'graduates' },
        { value: '12', label: 'students per group' },
        { value: '68%', label: 'employed within six months' },
        { value: '4.8', label: 'course rating' },
      ],
      categories: ['Design', 'Development', 'Analytics', 'Languages', 'Children', 'Corporate'],
      imagery: ['a classroom mid-session', 'student work on a wall', 'a teacher at the whiteboard'],
    },
    {
      id: 'creative',
      label: 'creative services',
      keywords: ['studio', 'design', 'branding', 'agency', 'portfolio', 'photograph', 'video', 'identity', 'creative', 'art direction', 'illustration', 'motion'],
      brands: ['Form', 'Studio Noir', 'Frame', 'Space', 'Measure'],
      nav: ['Work', 'Services', 'Studio', 'Process', 'Contact'],
      headlines: [
        'Brands worth scaling up',
        'We start with questions, not mood boards',
        'A system, not a set of pictures',
        'Work that still holds in three years',
      ],
      subtitles: [
        'Research and conversations with your team come first; the visual language follows from them.',
        'You get rules, files and the reasoning behind both — enough to carry on without us.',
        'A project usually runs four to eight weeks, and you see it at every stage.',
      ],
      items: [
        { title: 'Brand identity', meta: 'mark, palette, type, guidelines' },
        { title: 'Website', meta: 'prototype, design, handoff' },
        { title: 'Packaging', meta: 'design and print-ready files' },
        { title: 'Art direction', meta: 'shoots, illustration, oversight' },
        { title: 'Presentation', meta: 'story, slides, templates' },
        { title: 'Naming', meta: 'shortlist with availability checks' },
        { title: 'Motion', meta: 'logo animation and short cuts' },
        { title: 'Brand audit', meta: 'a written review with priorities' },
      ],
      stats: [
        { value: '8', label: 'years in practice' },
        { value: '60+', label: 'projects delivered' },
        { value: '3', label: 'projects at a time' },
        { value: '4–8', label: 'weeks per project' },
      ],
      categories: ['Branding', 'Web', 'Product', 'Packaging', 'Print', 'Motion'],
      imagery: ['a spread from the guidelines', 'work in situ on a real object', 'the studio at work'],
    },
    {
      id: 'sport',
      label: 'sport and fitness',
      keywords: ['gym', 'fitness', 'yoga', 'training', 'coach', 'sport', 'dance', 'pilates', 'crossfit', 'martial', 'workout', 'membership'],
      brands: ['Pulse', 'Prana', 'Rhythm', 'Form', 'Stride'],
      nav: ['Classes', 'Schedule', 'Coaches', 'Membership', 'Contact'],
      headlines: [
        'Turn up. The rest is our job.',
        'Progress you can measure',
        'A coach who remembers your name',
        'Built for people with jobs',
      ],
      subtitles: [
        'Your first session is an assessment, and the plan is written around what it finds.',
        'Classes run from 7am to 10pm, so training fits the day you actually have.',
        'Groups of eight at most — the coach corrects your form, not the room average.',
      ],
      items: [
        { title: 'Trial session', meta: 'assessment and a plan, free' },
        { title: 'Personal training', meta: 'one to one, by the hour' },
        { title: 'Group strength', meta: 'up to eight people' },
        { title: 'Yoga', meta: 'morning and evening streams' },
        { title: 'Cardio circuit', meta: 'forty-five minutes' },
        { title: 'Stretching', meta: 'mobility and recovery' },
        { title: 'Nutrition consult', meta: 'a plan without extremes' },
        { title: "Children's group", meta: 'ages 7 to 12' },
      ],
      stats: [
        { value: '600', label: 'members' },
        { value: '18', label: 'classes a week' },
        { value: '8', label: 'people per group' },
        { value: '5', label: 'years open' },
      ],
      categories: ['Strength', 'Cardio', 'Yoga', 'Dance', 'Martial arts', 'Children'],
      imagery: ['the floor during a class', 'a coach correcting form', 'equipment in morning light'],
    },
    {
      id: 'home',
      label: 'property and interiors',
      keywords: ['property', 'estate', 'apartment', 'house', 'renovation', 'interior', 'construction', 'architect', 'flat', 'rent', 'developer', 'refurbish'],
      brands: ['House·Line', 'Space', 'Solid', 'Project', 'Bearing'],
      nav: ['Listings', 'Services', 'Projects', 'Process', 'Contact'],
      headlines: [
        'Finished on the date we agreed',
        'An estimate that survives the build',
        'You see the flat before the walls go up',
        'One team from drawing to handover',
      ],
      subtitles: [
        'The estimate is fixed in the contract, and extras only happen with your signature.',
        'Weekly photo reports, so you know the state of the site without driving there.',
        'Design, engineering and construction under one roof — nobody to blame each other.',
      ],
      items: [
        { title: 'Two-bed, 68 m²', meta: 'city centre, ready to move in' },
        { title: 'House, 140 m²', meta: 'plot of 8, twenty minutes out' },
        { title: 'Studio, 34 m²', meta: 'renovated, furnished' },
        { title: 'Turnkey renovation', meta: 'from drawings to keys' },
        { title: 'Interior design', meta: 'layout, visuals, drawings' },
        { title: 'Cosmetic refresh', meta: 'four to six weeks' },
        { title: 'Site supervision', meta: 'weekly checks and reports' },
        { title: 'Commercial fit-out', meta: 'offices and retail' },
      ],
      stats: [
        { value: '120+', label: 'projects handed over' },
        { value: '0', label: 'missed deadlines this year' },
        { value: '3 years', label: 'workmanship guarantee' },
        { value: '11', label: 'years in the trade' },
      ],
      categories: ['Apartments', 'Houses', 'Commercial', 'Renovation', 'Design', 'Supervision'],
      imagery: ['a finished interior in daylight', 'the site mid-build', 'a plan on the table'],
    },
    {
      id: 'generic',
      label: 'project',
      keywords: [],
      brands: ['Meridian', 'Base', 'Contour', 'Azimuth', 'Clear'],
      nav: ['About', 'Services', 'Projects', 'Pricing', 'Contact'],
      headlines: [
        'Done properly, and on time',
        'A clear answer to a real problem',
        'Work you can hand to someone else',
        'Straightforward, from first call to delivery',
      ],
      subtitles: [
        'We agree the scope, the price and the date before anything starts, and hold all three.',
        'One person owns your project and answers for it — not a shared inbox.',
        'You see the work in progress, not a finished result you had no say in.',
      ],
      items: [
        { title: 'Initial consultation', meta: 'free, about an hour' },
        { title: 'Scoping', meta: 'a written brief and estimate' },
        { title: 'Standard package', meta: 'the usual case, fixed price' },
        { title: 'Extended package', meta: 'for non-standard work' },
        { title: 'Support', meta: 'monthly, cancel any time' },
        { title: 'Audit', meta: 'a review with priorities' },
        { title: 'Express turnaround', meta: 'when the date cannot move' },
        { title: 'Handover', meta: 'files, instructions, training' },
      ],
      stats: [
        { value: '150+', label: 'projects completed' },
        { value: '96%', label: 'delivered on schedule' },
        { value: '4.9', label: 'client rating' },
        { value: '7', label: 'years working' },
      ],
      categories: ['Getting started', 'Process', 'Results', 'Support', 'Team', 'Pricing'],
      imagery: ['the team at work', 'the result in context', 'a detail of the process'],
    },
  ],

  ctaByPurpose: {
    sell: ['Buy now', 'Add to basket', 'Checkout', 'Choose'],
    leads: ['Get in touch', 'Request a quote', 'Book a slot', 'Discuss the job'],
    present: ['Read more', 'About us', 'Open the deck', 'Find out more'],
    showcase: ['See the work', 'Open project', 'Full portfolio', 'Get in touch'],
    work: ['Get started', 'Open dashboard', 'Try it free', 'Sign in'],
    inform: ['Keep reading', 'All articles', 'Subscribe', 'Browse section'],
    engage: ['Take part', 'Subscribe', 'Watch', 'Join in'],
  },

  ctaSecondary: ['Learn more', 'How it works', 'Take a look', 'Ask a question'],

  featuresByPurpose: {
    sell: [
      { title: 'Honest pricing', text: 'The total is visible up front — nothing appears at the last step.' },
      { title: 'Shipped on time', text: 'Orders leave the same day and the tracking number follows immediately.' },
      { title: 'Returns, no questions', text: 'Thirty days to change your mind. We collect it ourselves.' },
      { title: 'Live stock levels', text: 'You only see what is genuinely on the shelf.' },
      { title: 'Two-year guarantee', text: 'Repaired or replaced, whichever you prefer.' },
      { title: 'Pay how you like', text: 'Card, instalments, or an invoice for companies.' },
    ],
    leads: [
      { title: 'Answered in 15 minutes', text: 'During working hours we call back almost straight away.' },
      { title: 'Quote before contract', text: 'You get costs and dates before you sign anything.' },
      { title: 'Fixed price', text: 'The figure in the contract does not move as the work goes on.' },
      { title: 'One person responsible', text: 'A named contact, not a shared mailbox.' },
      { title: 'Everything in writing', text: 'Contract, sign-off documents and a clear line of responsibility.' },
      { title: 'Free site visit', text: 'We assess the scope on site and charge nothing for it.' },
    ],
    present: [
      { title: 'Working since 2016', text: 'Through growth, downturns and a changed market.' },
      { title: 'An in-house team', text: 'Not subcontractors — people you know by name.' },
      { title: 'A visible process', text: 'You can see which stage the project is at and what comes next.' },
      { title: 'Our own production', text: 'Quality controlled at every step rather than inspected at the end.' },
      { title: 'Certified and licensed', text: 'Every permit in order and available on request.' },
      { title: 'Nationwide', text: 'Projects delivered in twenty-four regions.' },
    ],
    showcase: [
      { title: 'Research first', text: 'We start with data and interviews, not with references.' },
      { title: 'Systems, not pictures', text: 'You get a set of rules that keeps working after we leave.' },
      { title: 'We measure the result', text: 'Metrics after launch matter more than the presentation.' },
      { title: 'Three projects at once', text: 'We take no more, so each one keeps its depth.' },
      { title: 'End to end', text: 'Strategy, design, production and oversight.' },
      { title: 'An open process', text: 'You see the drafts, not just a finished result in a vacuum.' },
    ],
    work: [
      { title: 'Fits your process', text: 'Fields, statuses and roles follow how you already work.' },
      { title: 'No training needed', text: 'Usable from the first launch; the manual stays unopened.' },
      { title: 'Full change history', text: 'You can see who changed what, and roll it back.' },
      { title: 'Genuinely fast', text: 'Lists of tens of thousands of rows open instantly.' },
      { title: 'Granular permissions', text: 'Roles down to an individual field.' },
      { title: 'Export and API', text: 'The data is yours and leaves whenever you want it to.' },
    ],
    inform: [
      { title: 'Checked before published', text: 'Every piece is edited and fact-checked.' },
      { title: 'Five-minute reads', text: 'Short formats for people who do not have an hour.' },
      { title: 'No advertising', text: 'No banners and no sponsored paragraphs in the text.' },
      { title: 'Kept up to date', text: 'We revisit old pieces when the facts change.' },
      { title: 'Plain language', text: 'Complicated things explained without jargon.' },
      { title: 'Open archive', text: 'Everything readable without signing up.' },
    ],
    engage: [
      { title: 'A living community', text: 'A few thousand people who actually answer each other.' },
      { title: 'Something new weekly', text: 'A steady rhythm of posts and events.' },
      { title: 'You can join in', text: 'Not just watch — propose things and build them with us.' },
      { title: 'No barrier to entry', text: 'Come in at any level of experience.' },
      { title: 'We meet in person', text: 'An offline gathering once a month.' },
      { title: 'Open access', text: 'Free, with nothing expected in return.' },
    ],
  },

  steps: [
    { title: 'Enquiry', text: 'You send a short form or call, and we work out what is needed.' },
    { title: 'Discussion', text: 'We go through detail, dates and budget, and put it in an estimate.' },
    { title: 'The work', text: 'You hear from us at every stage and see the result as it forms.' },
    { title: 'Handover', text: 'We hand over the work and the instructions, and stay reachable.' },
  ],

  faq: [
    { title: 'What does it cost?', text: 'It depends on scope. A first estimate follows within a day of a short call.' },
    { title: 'How long does it take?', text: 'A typical project runs two to six weeks. The exact date goes in the contract.' },
    { title: 'How does payment work?', text: 'Usually in two parts: a deposit at the start and the balance on acceptance.' },
    { title: 'What if I do not like it?', text: 'Two rounds of revisions are included. If we still disagree, the deposit comes back.' },
    { title: 'Do you work with companies?', text: 'Yes, under contract with the full set of documents. VAT invoices on request.' },
    { title: 'What do you need from me?', text: 'One person to answer questions, and replies within a couple of days.' },
  ],

  testimonials: [
    { name: 'Anna Reut', role: 'founder, Noon', text: 'They moved quickly and never made us decide for them — options arrived with reasoning attached.' },
    { name: 'Igor Savelyev', role: 'marketing director', text: 'Enquiries were noticeably up in the first month, on the same advertising budget.' },
    { name: 'Maria Dolina', role: 'project lead', text: 'The documentation deserves a mention: our team picked the project up in two days without them.' },
    { name: 'Peter Ilyin', role: 'chain owner', text: 'The only contractor in five years who hit the date without being chased.' },
  ],
};

export default en;
